const VERSION = "4.3";
const ENDPOINT = "https://eopvkwhcgznvubesaszv.supabase.co/functions/v1/ai-chat-v3";
const FALLBACK_ENDPOINT = "https://eopvkwhcgznvubesaszv.supabase.co/functions/v1/cloudflare-ai-fallback";
const CLOUDFLARE_WORKER_ENDPOINT = "https://kds-ai-cloudflare.adam-kraus.workers.dev";
const messages=document.querySelector("#messages"),form=document.querySelector("#chat"),input=document.querySelector("#input"),updateApp=document.querySelector("#updateApp");
let messageCount=Number(sessionStorage.getItem("kds_ai_message_count")||"0"),adminToken="",adminMode=false,selectedModel=localStorage.getItem("kds_ai_model")||"default";
function setAdminStatus(){const s=document.querySelector("#modeStatus");if(s)s.textContent=adminMode?"Admin-Modus":"Online"}setAdminStatus();
const modelSelect=document.querySelector("#modelSelect");if(modelSelect){if([...modelSelect.options].some(o=>o.value===selectedModel))modelSelect.value=selectedModel;else{selectedModel="default";modelSelect.value="default"}modelSelect.addEventListener("change",()=>{selectedModel=modelSelect.value;localStorage.setItem("kds_ai_model",selectedModel)})}
function add(text,cls){const el=document.createElement("div");el.className="msg "+cls;el.textContent=text;messages.appendChild(el);el.scrollIntoView({behavior:"smooth",block:"nearest"})}
updateApp.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();updateApp.disabled=true;updateApp.textContent="Aktualisiere …";adminToken="";adminMode=false;const u=new URL(location.href);u.search="";u.searchParams.set("update",Date.now());location.href=u.toString()});
async function requestCloudflare(message){const r=await fetch(CLOUDFLARE_WORKER_ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({message})});const d=await r.json();if(!r.ok||!d.reply)throw Error(d.error||`Cloudflare-Fehler (${r.status})`);return d.reply}
async function requestMain(message,isFirstMessage){const r=await fetch(ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,isFirstMessage,adminToken,model:selectedModel})});const d=await r.json();if(!r.ok)throw Error(d.error||`Serverfehler (${r.status})`);return d}
form.addEventListener("submit",async e=>{e.preventDefault();e.stopPropagation();const message=input.value.trim();if(!message)return;if(message.toLowerCase()==="/exit"){input.value="";adminToken="";adminMode=false;setAdminStatus();add(message,"user");add("Admin-Modus beendet.","ai");input.focus();return}input.value="";add(message,"user");const n=message.toLowerCase().replace(/[!,.?]/g,"").trim();if(/^(hallo|hi|hey|guten morgen|guten tag|guten abend)$/.test(n)&&selectedModel!=="cloudflare"){messageCount++;sessionStorage.setItem("kds_ai_message_count",String(messageCount));add("Hallo! Wie kann ich dir helfen?","ai");input.focus();return}add("…","ai");const pending=messages.lastElementChild,isFirstMessage=messageCount===0;messageCount++;sessionStorage.setItem("kds_ai_message_count",String(messageCount));try{if(selectedModel==="cloudflare"){pending.textContent=await requestCloudflare(message);input.focus();return}let d;try{d=await requestMain(message,isFirstMessage)}catch(mainErr){console.warn("Primäres Modell fehlgeschlagen, Cloudflare-Fallback wird verwendet.",mainErr);pending.textContent="Wechsle zu Cloudflare AI …";pending.textContent=await requestCloudflare(message);input.focus();return}if(d.adminToken){adminToken=d.adminToken;adminMode=true;setAdminStatus();pending.textContent=d.reply||"Admin-Modus aktiviert."}if(d.mode==="exit"){adminToken="";adminMode=false;setAdminStatus()}if(!d.adminToken)pending.textContent=d.reply||d.error||"Keine Antwort erhalten."}catch(err){console.error(err);pending.textContent="Cloudflare AI ist momentan ebenfalls nicht erreichbar."}input.focus()});
